[package]
name = "taffy"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
tactical = { version = "0.4.0", git = "https://github.com/CoffeeShop-Development/tactical" }
# tactical = { version = "0.4.0", path = "../tactical" }
num = "0.4.3"
